"""
State Schemas for AutonomousAI LangGraph Orchestration.
Supports typed state transitions and persistence.
"""

from typing import Any, List, Dict, Optional, Literal, TypedDict
from pydantic import BaseModel, Field
import time


class Task(BaseModel):
    """Atomic task representation generated by the Planner."""
    id: str = Field(..., description="Unique task identifier e.g. task_1")
    title: str = Field(..., description="Short summary of the task")
    description: str = Field(..., description="Detailed instructions for implementation")
    target_files: List[str] = Field(default_factory=list, description="Files intended to be edited or created")
    dependencies: List[str] = Field(default_factory=list, description="Task IDs that must complete first")
    status: Literal["pending", "in_progress", "completed", "failed"] = Field(
        default="pending", description="Current execution status"
    )
    error_feedback: Optional[str] = Field(default=None, description="Feedback from failed execution")


class BudgetConfig(BaseModel):
    """Execution budget limits to prevent runaway loops."""
    max_iterations: int = Field(default=8, description="Maximum number of loop iterations")
    time_budget_minutes: int = Field(default=45, description="Total allowed runtime in minutes")
    start_timestamp: float = Field(default_factory=time.time, description="Unix timestamp of run start")

    def is_expired(self, current_iteration: int) -> bool:
        """Check if iteration or time limit has been exceeded."""
        elapsed_min = (time.time() - self.start_timestamp) / 60.0
        return current_iteration > self.max_iterations or elapsed_min >= self.time_budget_minutes


class ProcessRecord(BaseModel):
    """Record of a background dev server or process spawned by DevOps/Tester."""
    pid: int
    command: str
    port: Optional[int] = None
    start_time: float = Field(default_factory=time.time)
    status: Literal["running", "stopped", "failed"] = "running"


class IterationRecord(BaseModel):
    """Snapshot telemetry for a single iteration loop."""
    iteration_number: int
    timestamp: float = Field(default_factory=time.time)
    modified_files: List[str] = Field(default_factory=list)
    tests_passed: bool = False
    tests_failed_count: int = 0
    reviewer_passed: bool = False
    security_passed: bool = False
    confidence_score: float = 0.0
    error_summary: List[str] = Field(default_factory=list)
    patch_snapshot_path: Optional[str] = None


class ProjectState(TypedDict, total=False):
    """
    Central LangGraph State for AutonomousAI.
    Every agent reads and updates components of this state.
    """
    # Session metadata
    session_id: str
    project_path: str
    workspace_path: str
    goal: str
    constraints: List[str]
    acceptance_tests: List[str]

    # Analysis & Planning
    tech_stack: Dict[str, Any]
    ranked_context_files: List[Dict[str, Any]]
    plan: List[Dict[str, Any]]
    architecture: Dict[str, Any]

    # Implementation & Quality Gates
    modified_files: List[str]
    created_files: List[str]
    devops: Dict[str, Any]
    review: Dict[str, Any]
    security: Dict[str, Any]
    backend: Dict[str, Any]
    browser: Dict[str, Any]

    # Evaluation & Loop Decision
    evaluator: Dict[str, Any]
    feedback: Dict[str, Any]
    approved: bool
    confidence_score: float

    # Execution telemetry & guardrails
    iteration: int
    max_iterations: int
    start_time: float
    elapsed_minutes: float
    execution_mode: str  # 'auto' or 'assisted'
    status: str  # 'running', 'passed', 'failed', 'timeout', 'aborted'
    error_feedback: List[str]
    reports: List[str]
    active_processes: List[Dict[str, Any]]
